In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
homeprice_df = pd.read_csv('homeprices.csv')
homeprice_df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
median = homeprice_df.bedrooms.median()
median

4.0

In [4]:
homeprice_fillna = homeprice_df.fillna(median)
homeprice_fillna

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
 homeprice_fillna

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(homeprice_fillna.drop(['price'],axis = 1),homeprice_df.price)

LinearRegression()

In [7]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [8]:
reg.intercept_

221323.00186540408

In [9]:
reg.predict([[4000,5,8]])

array([760663.42675457])

In [10]:
4000*112.06244194+5*23388.88007794+8*-3231.71790863+221323.00186540408

760663.4267460641

# Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old



In [11]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [12]:
3000*112.06244194+3*23388.88007794+40*-3231.71790863+221323.00186540408

498408.2515740241

# Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

In [13]:
reg.predict([[2500,4,5]])

array([578876.03748933])

In [14]:
2500*112.06244194+4*23388.88007794+5*-3231.71790863+221323.00186540408

578876.0374840142